# Generated by Django 5.2.4 on 2026-05-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0017_tenant_agency_scope'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticketattachment',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='historicalticketreply',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_replies', to='agency_inventory.agency'),
        ),
    ]
