# Generated by Django 5.2.4 on 2026-05-01 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0019_business_agency_business_applieduniversity_business_and_more'),
        ('support', '0003_backfill_ticket_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='business',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.business'),
        ),
        migrations.AddField(
            model_name='historicalticketattachment',
            name='business',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.business'),
        ),
        migrations.AddField(
            model_name='historicalticketreply',
            name='business',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.business'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_support_tickets', to='agency_inventory.business'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_ticket_attachments', to='agency_inventory.business'),
        ),
        migrations.AddField(
            model_name='ticketreply',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_ticket_replies', to='agency_inventory.business'),
        ),
    ]
