# Generated by Django 5.2.4 on 2026-04-14 11:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStudentFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_file_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('passport_number', models.CharField(db_index=True, max_length=100)),
                ('passport_copy_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_whatsapp', models.CharField(max_length=30)),
                ('facebook_id_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('current_status', models.CharField(choices=[('FILE_RECEIVED', 'File Received'), ('PROCESSING', 'Processing'), ('APPLIED', 'Applied'), ('ENROLLED', 'Enrolled'), ('REJECTED', 'Rejected')], default='FILE_RECEIVED', max_length=20)),
                ('file_from', models.CharField(choices=[('AGENCY_OWN', "Agency's own"), ('SUB_AGENT', 'Sub agent'), ('DIRECT', 'Direct')], default='AGENCY_OWN', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical student file',
                'verbose_name_plural': 'historical student files',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_file_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('passport_number', models.CharField(max_length=100, unique=True)),
                ('passport_copy_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_whatsapp', models.CharField(max_length=30)),
                ('facebook_id_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('current_status', models.CharField(choices=[('FILE_RECEIVED', 'File Received'), ('PROCESSING', 'Processing'), ('APPLIED', 'Applied'), ('ENROLLED', 'Enrolled'), ('REJECTED', 'Rejected')], default='FILE_RECEIVED', max_length=20)),
                ('file_from', models.CharField(choices=[('AGENCY_OWN', "Agency's own"), ('SUB_AGENT', 'Sub agent'), ('DIRECT', 'Direct')], default='AGENCY_OWN', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_files', to='agency_inventory.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
