# Generated by Django 5.2.4 on 2026-04-14 12:19

from django.db import migrations, models
from django.utils.text import slugify


def backfill_university_related_slugs(apps, schema_editor):
    """
    Backfill slug for existing UniversityIntake and UniversityProgram rows.
    The generated value includes primary key to guarantee uniqueness.
    """
    UniversityIntake = apps.get_model("agency_inventory", "UniversityIntake")
    UniversityProgram = apps.get_model("agency_inventory", "UniversityProgram")

    for intake in UniversityIntake.objects.filter(slug__isnull=True):
        intake.slug = slugify(f"{intake.university_id}-{intake.intake_name}-{intake.id}")
        intake.save(update_fields=["slug"])

    for program in UniversityProgram.objects.filter(slug__isnull=True):
        program.slug = slugify(f"{program.university_id}-{program.program}-{program.id}")
        program.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0003_historicalstudentfile_studentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluniversityintake',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaluniversityprogram',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='universityintake',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(backfill_university_related_slugs, migrations.RunPython.noop),
    ]
