# Generated by Django 5.2.4 on 2026-04-15 11:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0004_historicaluniversityintake_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentfile',
            name='is_own_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='is_own_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_status',
            field=models.CharField(choices=[('FILE_RECEIVED', 'File Received'), ('IN_PROGRESS', 'In Progress'), ('FILE_OPENED', 'File Opened')], default='FILE_RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='current_status',
            field=models.CharField(choices=[('FILE_RECEIVED', 'File Received'), ('IN_PROGRESS', 'In Progress'), ('FILE_OPENED', 'File Opened')], default='FILE_RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalstudentfile',
            name='current_status',
            field=models.CharField(choices=[('FILE_RECEIVED', 'File Received'), ('IN_PROGRESS', 'In Progress'), ('FILE_OPENED', 'File Opened')], default='FILE_RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_files', to='agency_inventory.agency'),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='current_status',
            field=models.CharField(choices=[('FILE_RECEIVED', 'File Received'), ('IN_PROGRESS', 'In Progress'), ('FILE_OPENED', 'File Opened')], default='FILE_RECEIVED', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalUniversityProgramSubject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('track_name', models.CharField(blank=True, default='', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.universityprogram')),
            ],
            options={
                'verbose_name': 'historical university program subject',
                'verbose_name_plural': 'historical university program subjects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UniversityProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('track_name', models.CharField(blank=True, default='', max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='agency_inventory.universityprogram')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
