# Generated by Django 6.0.4 on 2026-04-15 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0006_studentcost_student_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officecost',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_costs', to='agency_inventory.agency'),
        ),
        migrations.AlterField(
            model_name='studentcost',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_costs', to='agency_inventory.agency'),
        ),
        migrations.AlterField(
            model_name='studentcost',
            name='student_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='agency_inventory.studentfile'),
        ),
    ]
