# Generated by Django 5.2.4 on 2026-04-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0011_remove_historicalstudentfile_intake_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applieduniversity',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='applieduniversity',
            name='subjects',
        ),
        migrations.AddField(
            model_name='applieduniversity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_universities', to='agency_inventory.studentfilesubject'),
        ),
        migrations.AddField(
            model_name='historicalapplieduniversity',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.studentfilesubject'),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='student_files', to='agency_inventory.studentfileattachment'),
        ),
    ]
