# Generated by Django 5.2.4 on 2026-04-16 09:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def migrate_country_and_applied_university_relations(apps, schema_editor):
    Country = apps.get_model("agency_inventory", "Country")
    University = apps.get_model("agency_inventory", "University")
    HistoricalUniversity = apps.get_model("agency_inventory", "HistoricalUniversity")
    AppliedUniversity = apps.get_model("agency_inventory", "AppliedUniversity")
    HistoricalAppliedUniversity = apps.get_model("agency_inventory", "HistoricalAppliedUniversity")

    country_name_to_id = {}

    def get_country_id(country_name):
        normalized_country_name = (country_name or "").strip()
        if not normalized_country_name:
            return None
        if normalized_country_name in country_name_to_id:
            return country_name_to_id[normalized_country_name]
        country_obj, _ = Country.objects.get_or_create(name=normalized_country_name)
        country_name_to_id[normalized_country_name] = country_obj.id
        return country_obj.id

    for university_obj in University.objects.all().iterator():
        country_id = get_country_id(university_obj.country)
        if country_id:
            # Keep values numeric as text before char->FK type conversion.
            university_obj.country = str(country_id)
            university_obj.save(update_fields=["country"])

    for historical_university_obj in HistoricalUniversity.objects.all().iterator():
        country_id = get_country_id(historical_university_obj.country)
        if country_id:
            historical_university_obj.country = str(country_id)
            historical_university_obj.save(update_fields=["country"])

    university_name_to_obj = {}
    for university_obj in University.objects.all().iterator():
        normalized_university_name = (university_obj.university_name or "").strip().lower()
        if normalized_university_name and normalized_university_name not in university_name_to_obj:
            university_name_to_obj[normalized_university_name] = university_obj

    for applied_university_obj in AppliedUniversity.objects.all().iterator():
        normalized_university_name = (applied_university_obj.university_name or "").strip().lower()
        matched_university = university_name_to_obj.get(normalized_university_name)
        if matched_university:
            applied_university_obj.university_id = matched_university.id
            if matched_university.country:
                applied_university_obj.country_id = int(matched_university.country)
            applied_university_obj.save(update_fields=["university", "country"])

    for historical_applied_university_obj in HistoricalAppliedUniversity.objects.all().iterator():
        normalized_university_name = (historical_applied_university_obj.university_name or "").strip().lower()
        matched_university = university_name_to_obj.get(normalized_university_name)
        if matched_university:
            historical_applied_university_obj.university_id = matched_university.id
            if matched_university.country:
                historical_applied_university_obj.country_id = int(matched_university.country)
            historical_applied_university_obj.save(update_fields=["university", "country"])


def reverse_noop(apps, schema_editor):
    """
    No safe reverse for FK data backfill.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0012_remove_applieduniversity_attachments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='applieduniversity',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_universities', to='agency_inventory.university'),
        ),
        migrations.AddField(
            model_name='historicalapplieduniversity',
            name='university',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.university'),
        ),
        migrations.AddField(
            model_name='applieduniversity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_universities', to='agency_inventory.country'),
        ),
        migrations.AddField(
            model_name='historicalapplieduniversity',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.country'),
        ),
        migrations.RunPython(
            code=migrate_country_and_applied_university_relations,
            reverse_code=reverse_noop,
        ),
        migrations.AlterField(
            model_name='historicaluniversity',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='agency_inventory.country'),
        ),
        migrations.RemoveField(
            model_name='applieduniversity',
            name='university_name',
        ),
        migrations.RemoveField(
            model_name='historicalapplieduniversity',
            name='university_name',
        ),
        migrations.CreateModel(
            name='HistoricalCountry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical country',
                'verbose_name_plural': 'historical countrys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
