# Generated by Django 5.2.4 on 2026-04-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0013_remove_applieduniversity_university_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfilesubject',
            name='deleted_by',
        ),
        migrations.AlterField(
            model_name='applieduniversity',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_universities', to='agency_inventory.universityprogramsubject'),
        ),
        migrations.AlterField(
            model_name='historicalapplieduniversity',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.universityprogramsubject'),
        ),
        migrations.DeleteModel(
            name='HistoricalStudentFileSubject',
        ),
        migrations.DeleteModel(
            name='StudentFileSubject',
        ),
    ]
