# Generated by Django 5.2.4 on 2026-04-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0014_remove_studentfilesubject_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='trade_license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='trade_license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
