# Generated by Django 5.2.4 on 2026-05-01 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0016_program_and_universityprogram_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='university',
            name='unique_university_name_country',
        ),
        migrations.AddField(
            model_name='applieduniversity',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_applied_universities', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='country',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_countries', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='historicalapplieduniversity',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='historicalstudentfileattachment',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='historicaluniversity',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='historicaluniversityintake',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='historicaluniversityprogram',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='historicaluniversityprogramsubject',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='program',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_programs', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='studentfileattachment',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_file_attachments', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='university',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_universities', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='universityintake',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_intakes', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_program_links', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='universityprogramsubject',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_program_subjects', to='agency_inventory.agency'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcountry',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='passport_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalstudentfile',
            name='passport_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_files', to='agency_inventory.agency'),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='passport_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('agency', 'name'), name='unique_country_name_per_agency'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('agency', 'passport_number'), name='unique_customer_passport_per_agency'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('agency', 'name'), name='unique_program_name_per_agency'),
        ),
        migrations.AddConstraint(
            model_name='studentfile',
            constraint=models.UniqueConstraint(fields=('agency', 'passport_number'), name='unique_studentfile_passport_per_agency'),
        ),
        migrations.AddConstraint(
            model_name='university',
            constraint=models.UniqueConstraint(fields=('agency', 'university_name', 'country'), name='unique_university_name_country_per_agency'),
        ),
    ]
