# Generated by Django 5.2.4 on 2026-05-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0021_backfill_business_from_created_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='university',
            name='unique_university_name_country_per_agency',
        ),
    ]
