# Generated by Django 5.2.4 on 2026-05-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0022_remove_university_unique_university_name_country_per_agency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='country',
            name='unique_country_name_per_agency',
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_passport_per_agency',
        ),
        migrations.RemoveConstraint(
            model_name='program',
            name='unique_program_name_per_agency',
        ),
        migrations.RemoveConstraint(
            model_name='studentfile',
            name='unique_studentfile_passport_per_agency',
        ),
        migrations.RemoveConstraint(
            model_name='universityintake',
            name='unique_intake_per_university',
        ),
        migrations.RemoveConstraint(
            model_name='universityprogram',
            name='unique_program_per_university',
        ),
    ]
