# Generated by Django 5.2.4 on 2026-05-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0025_student_application_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='admission_letter_received',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='admission_letter_received_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='dhl_received_from_university',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='dhl_received_from_university_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='dhl_sent_to_university',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='dhl_sent_to_university_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='enrolled',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='enrolled_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='interview_completed',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='interview_completed_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='interview_scheduled',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='interview_scheduled_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='tuition_fee_paid',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='tuition_fee_paid_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='visa_received',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='visa_received_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='visa_rejected',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalstudentapplicationprogress',
            name='visa_rejected_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='admission_letter_received',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='admission_letter_received_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='dhl_received_from_university',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='dhl_received_from_university_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='dhl_sent_to_university',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='dhl_sent_to_university_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='enrolled',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='enrolled_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='interview_completed',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='interview_completed_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='interview_scheduled',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='interview_scheduled_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='tuition_fee_paid',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='tuition_fee_paid_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='visa_received',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='visa_received_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='visa_rejected',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplicationprogress',
            name='visa_rejected_manual',
            field=models.BooleanField(default=False),
        ),
    ]
