# Generated by Django 5.2.4 on 2026-05-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0026_expand_student_application_progress_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='avg_tuition_public',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='ielts_required',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='intake_periods',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='living_cost',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='scholarship',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='visa_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='country',
            name='work_rights',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='avg_tuition_public',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='ielts_required',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='intake_periods',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='language',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='living_cost',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='scholarship',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='visa_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='work_rights',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaluniversity',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicaluniversity',
            name='minimum_ielts_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum IELTS score required for this university.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='minimum_ielts_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum IELTS score required for this university.', max_digits=3, null=True),
        ),
    ]
