# Generated by Django 5.2.4 on 2026-05-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0027_country_avg_tuition_public_country_ielts_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentfile',
            name='is_website_submission',
            field=models.BooleanField(default=False, help_text='True when this file is submitted from the public website flow.'),
        ),
        migrations.AddField(
            model_name='historicalstudentfile',
            name='website_submission_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text='Stable public reference id for website-submitted student files.', null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='is_website_submission',
            field=models.BooleanField(default=False, help_text='True when this file is submitted from the public website flow.'),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='website_submission_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Stable public reference id for website-submitted student files.', null=True, unique=True),
        ),
    ]
