# Generated by Django 6.0.4 on 2026-05-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0028_historicalstudentfile_is_website_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentfile',
            name='passport_photo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='passport_photo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
