# Generated by Django 5.2.4 on 2026-05-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0030_studentfile_hanseo_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentfile',
            name='application_statement',
            field=models.TextField(blank=True, default='', help_text='Statement of purpose line on page 1 of the Hanseo pack; a sensible default is applied in the PDF if empty.'),
        ),
        migrations.AlterField(
            model_name='historicalstudentfile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', help_text='Stored like Customer; shown on Hanseo and similar admission forms.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalstudentfile',
            name='translated_documents_note',
            field=models.CharField(blank=True, default='', help_text='Short list for the Hanseo translation form (e.g. APPLICANT NID, PARENTS NID).', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='education_background',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='family_particulars',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='translator_profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
