# Generated by Django 5.2.4 on 2026-05-09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models
from django.utils.dateparse import parse_date


def _clean_text(value):
    if value is None:
        return ""
    return str(value)


def _clean_date(value):
    if not value:
        return None
    if hasattr(value, "isoformat"):
        return value
    if isinstance(value, str):
        return parse_date(value.strip())
    return None


def copy_json_rows(apps, _schema_editor):
    StudentFile = apps.get_model("agency_inventory", "StudentFile")
    StudentEducationBackground = apps.get_model("agency_inventory", "StudentEducationBackground")
    StudentFamilyParticular = apps.get_model("agency_inventory", "StudentFamilyParticular")

    education_rows = []
    family_rows = []
    for student_file in StudentFile.objects.all().iterator():
        raw_education = student_file.education_background or []
        if isinstance(raw_education, list):
            for index, row in enumerate(raw_education):
                if not isinstance(row, dict):
                    continue
                education_rows.append(
                    StudentEducationBackground(
                        student_file_id=student_file.id,
                        degree=_clean_text(row.get("degree")),
                        institution=_clean_text(row.get("institution")),
                        study_period=_clean_text(row.get("study_period")),
                        result=_clean_text(row.get("result")),
                        graduation_date=_clean_date(row.get("graduation_date")),
                        institution_phone=_clean_text(row.get("institution_phone")),
                        admission_date=_clean_date(row.get("admission_date")),
                        sort_order=index,
                    )
                )

        raw_family = student_file.family_particulars or []
        if isinstance(raw_family, list):
            for index, row in enumerate(raw_family):
                if not isinstance(row, dict):
                    continue
                family_rows.append(
                    StudentFamilyParticular(
                        student_file_id=student_file.id,
                        relation=_clean_text(row.get("relation")),
                        name=_clean_text(row.get("name")),
                        date_of_birth=_clean_date(row.get("date_of_birth")),
                        occupation=_clean_text(row.get("occupation")),
                        monthly_income=_clean_text(row.get("monthly_income")),
                        workplace=_clean_text(row.get("workplace")),
                        workplace_phone=_clean_text(row.get("workplace_phone")),
                        sort_order=index,
                    )
                )

    if education_rows:
        StudentEducationBackground.objects.bulk_create(education_rows, batch_size=500)
    if family_rows:
        StudentFamilyParticular.objects.bulk_create(family_rows, batch_size=500)


def noop_reverse(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("agency_inventory", "0031_sync_studentfile_help_texts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalStudentEducationBackground",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("degree", models.CharField(max_length=150)),
                ("institution", models.CharField(blank=True, default="", max_length=255)),
                ("study_period", models.CharField(blank=True, default="", max_length=100)),
                ("result", models.CharField(blank=True, default="", max_length=100)),
                ("graduation_date", models.DateField(blank=True, null=True)),
                ("institution_phone", models.CharField(blank=True, default="", max_length=50)),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("deleted_by", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("student_file", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="agency_inventory.studentfile")),
            ],
            options={
                "verbose_name": "historical student education background",
                "verbose_name_plural": "historical student education backgrounds",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStudentFamilyParticular",
            fields=[
                ("id", models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("relation", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, default="", max_length=150)),
                ("monthly_income", models.CharField(blank=True, default="", max_length=100)),
                ("workplace", models.CharField(blank=True, default="", max_length=255)),
                ("workplace_phone", models.CharField(blank=True, default="", max_length=50)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("deleted_by", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("student_file", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="agency_inventory.studentfile")),
            ],
            options={
                "verbose_name": "historical student family particular",
                "verbose_name_plural": "historical student family particulars",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="StudentEducationBackground",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("degree", models.CharField(max_length=150)),
                ("institution", models.CharField(blank=True, default="", max_length=255)),
                ("study_period", models.CharField(blank=True, default="", max_length=100)),
                ("result", models.CharField(blank=True, default="", max_length=100)),
                ("graduation_date", models.DateField(blank=True, null=True)),
                ("institution_phone", models.CharField(blank=True, default="", max_length=50)),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("student_file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="education_background_rows", to="agency_inventory.studentfile")),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudentFamilyParticular",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("relation", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, default="", max_length=150)),
                ("monthly_income", models.CharField(blank=True, default="", max_length=100)),
                ("workplace", models.CharField(blank=True, default="", max_length=255)),
                ("workplace_phone", models.CharField(blank=True, default="", max_length=50)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("student_file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="family_particular_rows", to="agency_inventory.studentfile")),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.RunPython(copy_json_rows, noop_reverse),
        migrations.RemoveField(
            model_name="historicalstudentfile",
            name="education_background",
        ),
        migrations.RemoveField(
            model_name="historicalstudentfile",
            name="family_particulars",
        ),
        migrations.RemoveField(
            model_name="studentfile",
            name="education_background",
        ),
        migrations.RemoveField(
            model_name="studentfile",
            name="family_particulars",
        ),
    ]
