# Generated by Django 5.2.4 on 2026-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0033_studentfile_nid_payments_family_nids'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentfamilyparticular',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentfamilyparticular',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
