# Generated by Django 6.0.4 on 2026-05-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0034_historicalstudentfamilyparticular_is_sponsor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudenteducationbackground',
            name='degree',
            field=models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('BACHELOR', 'Bachelor'), ('MASTERS', "Master's"), ('PHD', 'PhD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalstudentfile',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentfile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentfile',
            name='passport_copy_url',
            field=models.URLField(blank=True, help_text="Passport's copy/scan URL", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentfile',
            name='passport_photo_url',
            field=models.URLField(blank=True, help_text='Passport size photo URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studenteducationbackground',
            name='degree',
            field=models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('BACHELOR', 'Bachelor'), ('MASTERS', "Master's"), ('PHD', 'PhD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='passport_copy_url',
            field=models.URLField(blank=True, help_text="Passport's copy/scan URL", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='passport_photo_url',
            field=models.URLField(blank=True, help_text='Passport size photo URL', max_length=1000, null=True),
        ),
    ]
