# Generated by Django 6.0.4 on 2026-05-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0035_alter_historicalstudenteducationbackground_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudentfamilyparticular',
            name='monthly_income',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentfamilyparticular',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentfamilyparticular',
            name='nid_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentfamilyparticular',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentfamilyparticular',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentfamilyparticular',
            name='workplace',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentfamilyparticular',
            name='workplace_phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentfamilyparticular',
            name='monthly_income',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentfamilyparticular',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentfamilyparticular',
            name='nid_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentfamilyparticular',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studentfamilyparticular',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentfamilyparticular',
            name='workplace',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentfamilyparticular',
            name='workplace_phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
