# Generated by Django 6.0.4 on 2026-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0037_studentfile_signature_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='watermark_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='watermark_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudentfile',
            name='signature_url',
            field=models.URLField(blank=True, help_text='Student signature image URL', max_length=1000, null=True),
        ),
    ]
