# Generated by Django 5.2.4 on 2026-05-01 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0018_backfill_tenant_agency'),
        ('authentication', '0005_historicalnotification_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_student_file',
            field=models.OneToOneField(blank=True, help_text='When user_type is STUDENT, this file is the only student-file row this user may access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_user', to='agency_inventory.studentfile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('AGENCY_SUPER_ADMIN', 'Agency Super Admin'), ('AGENCY_EMPLOYEE', 'Agency Employee'), ('B2B_AGENT', 'B2B Agent'), ('B2B_AGENT_EMPLOYEE', 'B2B Agent Employee'), ('STUDENT', 'Student')], help_text='Business user category used by the user-management UI.', max_length=30, null=True),
        ),
    ]
