# Generated by Django 5.2.4 on 2026-05-01 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0019_business_agency_business_applieduniversity_business_and_more'),
        ('authentication', '0006_user_linked_student_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_business',
            field=models.ForeignKey(blank=True, help_text="Optional explicit tenant scope. When unset for staff users it is inferred from parent_agency.business (or student's file business for portal accounts).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_users', to='agency_inventory.business'),
        ),
    ]
