# Generated by Django 4.2.20 on 2025-04-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_permission_code_alter_role_name_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(help_text='e.g., can_bulk_import_product', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, 'Other'), (1, 'Female'), (0, 'Male')], default=0),
        ),
    ]
