# Generated by Django 5.2.4 on 2026-05-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0020_backfill_business_tenant_data'),
        ('authentication', '0008_backfill_user_parent_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotification',
            name='business',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.business'),
        ),
        migrations.AddField(
            model_name='notification',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='agency_inventory.business'),
        ),
    ]
