# Generated by Django 4.2.20 on 2025-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_confirmation_options_alter_merchant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, 'Other'), (0, 'Male'), (1, 'Female')], default=0),
        ),
    ]
