# Generated by Django 4.2.20 on 2025-05-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_section_permission_slug_alter_permission_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Female'), (2, 'Other'), (0, 'Male')], default=0),
        ),
    ]
