# Generated by Django 4.2.20 on 2025-05-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, 'Other'), (1, 'Female'), (0, 'Male')], default=0),
        ),
    ]
