# Generated by Django 4.2.20 on 2025-06-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Female'), (0, 'Male'), (2, 'Other')], default=0),
        ),
    ]
