# Generated by Django 4.2.20 on 2025-06-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_role_options_role_created_at_role_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Female'), (0, 'Male'), (2, 'Other')], default=0),
        ),
    ]
