# Generated by Django 4.2.20 on 2025-07-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_permission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrole',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'Male'), (2, 'Other'), (1, 'Female')], default=0),
        ),
    ]
