# Generated by Django 5.2.4 on 2025-07-14 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, 'Other'), (1, 'Female'), (0, 'Male')], default=0),
        ),
    ]
