# Generated by Django 5.2.4 on 2025-09-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, 'Other'), (1, 'Female'), (0, 'Male')], default=0),
        ),
    ]
