# Generated by Django 5.2.4 on 2025-10-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, 'Other'), (1, 'Female'), (0, 'Male')], default=0),
        ),
    ]
