# Generated by Django 5.2.4 on 2025-11-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Female'), (0, 'Male'), (2, 'Other')], default=0),
        ),
    ]
