# Generated by Django 5.2.4 on 2026-04-23 07:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_historicalinvoice_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoicelineitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.RunSQL(
            sql="UPDATE order_invoicelineitem SET amount = line_total WHERE line_total IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="UPDATE order_historicalinvoicelineitem SET amount = line_total WHERE line_total IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='historicalinvoicelineitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicelineitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicelineitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='historicalinvoicelineitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='unit_price',
        ),
    ]
