# Generated by Django 5.2.4 on 2026-05-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0017_tenant_agency_scope'),
        ('order', '0003_remove_historicalinvoicelineitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoiceattachment',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='historicalinvoicelineitem',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='invoiceattachment',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_attachments', to='agency_inventory.agency'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line_items', to='agency_inventory.agency'),
        ),
    ]
