# Generated by Django 5.2.4 on 2026-05-01 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_inventory', '0019_business_agency_business_applieduniversity_business_and_more'),
        ('order', '0005_backfill_invoice_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='business',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.business'),
        ),
        migrations.AddField(
            model_name='historicalinvoiceattachment',
            name='business',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.business'),
        ),
        migrations.AddField(
            model_name='historicalinvoicelineitem',
            name='business',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency_inventory.business'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_invoices', to='agency_inventory.business'),
        ),
        migrations.AddField(
            model_name='invoiceattachment',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_invoice_attachments', to='agency_inventory.business'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_invoice_line_items', to='agency_inventory.business'),
        ),
    ]
