# Generated by Django 5.2.4 on 2026-05-01 14:53

from django.db import migrations, models


def backfill_invoice_agency_owner_flag(apps, schema_editor):
    """Mark existing invoices created by AGENCY_SUPER_ADMIN / AGENCY_EMPLOYEE users."""
    Invoice = apps.get_model("order", "Invoice")
    User = apps.get_model("authentication", "User")
    agency_staff_qs = User.objects.filter(user_type__in=("AGENCY_SUPER_ADMIN", "AGENCY_EMPLOYEE")).values_list(
        "pk", flat=True
    )
    Invoice.objects.filter(created_by_id__in=agency_staff_qs).update(is_created_by_agency_owner=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_backfill_invoice_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='is_created_by_agency_owner',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the invoice was created by agency-side staff (super admin or employee). Agency users only list rows with this flag set; B2B-issued invoices stay False.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_created_by_agency_owner',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the invoice was created by agency-side staff (super admin or employee). Agency users only list rows with this flag set; B2B-issued invoices stay False.'),
        ),
        migrations.RunPython(backfill_invoice_agency_owner_flag, noop_reverse),
    ]
