# Generated by Django 6.0.4 on 2026-05-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_invoice_is_created_by_business_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='is_created_by_business_owner',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the invoice was created by business-tier staff (AGENCY_SUPER_ADMIN or AGENCY_EMPLOYEE). They only list invoices with this flag; B2B-issued invoices stay False.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_created_by_business_owner',
            field=models.BooleanField(db_index=True, default=False, help_text='True when the invoice was created by business-tier staff (AGENCY_SUPER_ADMIN or AGENCY_EMPLOYEE). They only list invoices with this flag; B2B-issued invoices stay False.'),
        ),
    ]
